name: Create Release Zip

on:
  push:
    tags:
      - '*'

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up zip file name
        id: zipinfo
        run: |
          ZIP_NAME="ammonia-to-water_${GITHUB_REF##*/}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Create zip archive
        run: |
          mkdir -p ammonia-to-water
          cp -r * ammonia-to-water/
          zip -r "$ZIP_NAME" ammonia-to-water -x "ammonia-to-water/.git/*" "ammonia-to-water/.github/*" "ammonia-to-water/.gitignore" "ammonia-to-water/util/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
