name: Create Release Zip

on:
  push:
    tags:
      - '*'

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up zip file name
        id: zipinfo
        run: |
          ZIP_NAME="ammonia-to-water_${GITHUB_REF##*/}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Create zip archive
        run: |
          TEMP_DIR=$(mktemp -d)
          mkdir -p "$TEMP_DIR/ammonia-to-water"
          rsync -av --exclude .git/ --exclude .github/ --exclude util/ --exclude .gitignore ./ "$TEMP_DIR/ammonia-to-water/"
          zip -r "$ZIP_NAME" "$TEMP_DIR/ammonia-to-water"
          rm -rf "$TEMP_DIR"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
